### ISSUE TITLE
Investigate adding GenX to validation workflow

### ISSUE THREAD

**Issue by andyfaff** [reflectivity/analysis#14]
@aglavic it'd be great to get your help on this.

**Comment by aglavic** [comment]
Yes, @andyfaff. I'll try to look at the implementation the next time I come to work on GenX. There hasn't been any unit testing in genx when I took it over, so I was planning to do some validation anyway. I fear I won't be able to do it before I can release the final version 3.0, as there are a lot of bugs to fix, first.

**Comment by andyfaff** [comment]
No worries, I just wanted to encourage everyone to work together on this.

**Comment by andyfaff** [comment]
ping @aglavic

**Comment by andyfaff** [comment]
I pinged before I had the full facts. The genx validation was added this morning.

**Comment by aglavic** [comment]
Nice timing, I just committed it without thinking of this issue :-)
