### ISSUE TITLE
potential error in analysis/tutorials/tutorial1_genx.ipynb

### ISSUE THREAD

**Issue by ambarb** [reflectivity/analysis#62]
It looks like a cell was changed to markdown and some syntax was lost.  Perhaps even some code is missing
![Screen Shot 2022-03-25 at 12 55 22 PM](https://user-images.githubusercontent.com/13630233/160167097-cb35f89d-d719-4210-a301-92c87aa020b9.png)
.

**Comment by arm61** [comment]
@aglavic I guess you are the person to help on this?

**Comment by aglavic** [comment]
This cell is not markdown, it's the Jupyter Notebook representation of the object (_repr_html_).

There was, however, a change in the API that I have now fixed, so the tutorial should work with the latest GenX build.
